import type { Profile } from "../types/user";
import type { Ticket } from "../types/ticket";

const now = new Date("2026-05-14T10:30:00.000Z");

function daysAgo(days: number) {
  const date = new Date(now);
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

export const demoProfiles: Profile[] = [
  {
    id: "demo-leader",
    name: "Sam",
    email: "sam@stilldesk.local",
    role: "supreme_leader",
    work_role: "product_manager",
    department: "product",
    preferred_view: "dashboard",
    preferred_filters: ["needs_attention", "blocked", "waiting_verification", "unassigned", "all"],
    onboarding_completed: false,
  },
  {
    id: "demo-dev-a",
    name: "Jordan Lee",
    email: "jordan@stilldesk.local",
    role: "developer",
    work_role: "developer",
    department: "engineering",
    preferred_view: "tickets",
    preferred_filters: ["assigned", "being_fixed", "blocked", "backend", "frontend"],
    onboarding_completed: true,
  },
  {
    id: "demo-dev-b",
    name: "Casey Park",
    email: "casey@stilldesk.local",
    role: "developer",
    work_role: "developer",
    department: "engineering",
    preferred_view: "board",
    preferred_filters: ["assigned", "blocked", "in_progress", "fixed"],
    onboarding_completed: true,
  },
  {
    id: "demo-reporter",
    name: "Alex Rivera",
    email: "alex@stilldesk.local",
    role: "reporter",
    work_role: "support_qa",
    department: "support",
    preferred_view: "tickets",
    preferred_filters: ["mine", "waiting_verification", "blocked", "all"],
    onboarding_completed: true,
  },
];

export const demoUser = demoProfiles[0];

export const previewUser: Profile = {
  id: "preview-user",
  name: "Visitor",
  email: "",
  role: "supreme_leader",
  work_role: "product_manager",
  department: "product",
  preferred_view: "dashboard",
  preferred_filters: ["needs_attention", "blocked", "all"],
  onboarding_completed: false,
};

const baseTickets: Ticket[] = [
  {
    id: "SD-1048",
    title: "Long text input causes response to stall",
    description:
      "When the input exceeds roughly 2 000 characters the next reply stalls silently. No error is shown to the user.",
    category: "backend",
    priority: "high",
    status: "blocked",
    created_by: "demo-reporter",
    assigned_to: "demo-dev-a",
    module: "Messaging",
    dependency_note: "Waiting on stream timeout details from server logs.",
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
    fixed_at: null,
    verified_at: null,
  },
  {
    id: "SD-1047",
    title: "Logo detection skips valid SVG files on first pass",
    description: "SVG files that pass our validation rules are silently skipped during the first detection pass. PNG files work correctly.",
    category: "frontend",
    priority: "medium",
    status: "assigned",
    created_by: "demo-reporter",
    assigned_to: "demo-dev-b",
    module: "Uploads",
    dependency_note: null,
    created_at: daysAgo(4),
    updated_at: daysAgo(2),
    fixed_at: null,
    verified_at: null,
  },
  {
    id: "SD-1046",
    title: "Record count in header does not match table rows",
    description: "The summary header shows 120 records but the table renders only 116 rows. Discrepancy is consistent across refreshes.",
    category: "data",
    priority: "high",
    status: "in_progress",
    created_by: "demo-leader",
    assigned_to: "demo-dev-a",
    module: "Reports",
    dependency_note: null,
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
    fixed_at: null,
    verified_at: null,
  },
  {
    id: "SD-1045",
    title: "Duplicate contacts when sources overlap",
    description: "When two data sources resolve to the same person, duplicate contact records are created instead of being merged.",
    category: "backend",
    priority: "medium",
    status: "open",
    created_by: "demo-reporter",
    assigned_to: null,
    module: "Contacts",
    dependency_note: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
    fixed_at: null,
    verified_at: null,
  },
  {
    id: "SD-1044",
    title: "Preview pane blank after switching template tone",
    description: "Switching the template tone from Concise to Friendly leaves the preview pane blank. Refreshing the page restores it.",
    category: "frontend",
    priority: "medium",
    status: "fixed",
    created_by: "demo-leader",
    assigned_to: "demo-dev-b",
    module: "Templates",
    dependency_note: null,
    created_at: daysAgo(8),
    updated_at: daysAgo(1),
    fixed_at: daysAgo(1),
    verified_at: null,
  },
  {
    id: "SD-1043",
    title: "Variable placeholder not replaced in second paragraph",
    description: "The {{company}} placeholder is not substituted in the second paragraph of generated content. First paragraph is fine.",
    category: "copy",
    priority: "low",
    status: "verified",
    created_by: "demo-reporter",
    assigned_to: "demo-dev-a",
    module: "Content",
    dependency_note: null,
    created_at: daysAgo(10),
    updated_at: daysAgo(2),
    fixed_at: daysAgo(3),
    verified_at: daysAgo(2),
  },
  {
    id: "SD-1042",
    title: "Step owner resets after page refresh",
    description: "Changing the step owner saves visually but a hard refresh reverts it to the previous owner. DB write appears to fail silently.",
    category: "backend",
    priority: "blocker",
    status: "blocked",
    created_by: "demo-leader",
    assigned_to: "demo-dev-b",
    module: "Workflows",
    dependency_note: "Needs a migration decision for ownership history table.",
    created_at: daysAgo(9),
    updated_at: daysAgo(1),
    fixed_at: null,
    verified_at: null,
  },
  {
    id: "SD-1041",
    title: "Primary CTA overlaps plan label on small screens",
    description: "On 390 px viewports the primary call-to-action button overlaps the plan comparison label directly below it.",
    category: "design",
    priority: "medium",
    status: "closed",
    created_by: "demo-reporter",
    assigned_to: "demo-dev-a",
    module: "Pricing",
    dependency_note: null,
    created_at: daysAgo(14),
    updated_at: daysAgo(4),
    fixed_at: daysAgo(5),
    verified_at: daysAgo(4),
  },
];

export const demoTickets: Ticket[] = baseTickets.map((ticket): Ticket => ({
  ...ticket,
  reporter: demoProfiles.find((profile) => profile.id === ticket.created_by),
  assignee: demoProfiles.find((profile) => profile.id === ticket.assigned_to) ?? null,
  comments: [
    {
      id: `${ticket.id}-c1`,
      ticket_id: ticket.id,
      user_id: ticket.created_by,
      comment: "Raised here so it does not drift across chat.",
      tagged_user_id: ticket.assigned_to,
      created_at: ticket.created_at,
      user: demoProfiles.find((profile) => profile.id === ticket.created_by),
      tagged_user: demoProfiles.find((profile) => profile.id === ticket.assigned_to) ?? null,
    },
  ],
  attachments: [],
  activity: [
    {
      id: `${ticket.id}-a1`,
      ticket_id: ticket.id,
      action: "created",
      old_value: null,
      new_value: ticket.status,
      user_id: ticket.created_by,
      created_at: ticket.created_at,
      user: demoProfiles.find((profile) => profile.id === ticket.created_by),
    },
    ...(ticket.assigned_to
      ? [
          {
            id: `${ticket.id}-a2`,
            ticket_id: ticket.id,
            action: "assigned_to",
            old_value: null,
            new_value: ticket.assigned_to,
            user_id: ticket.created_by,
            created_at: ticket.updated_at,
            user: demoProfiles.find((profile) => profile.id === ticket.created_by),
          },
        ]
      : []),
    ...(ticket.fixed_at
      ? [
          {
            id: `${ticket.id}-a3`,
            ticket_id: ticket.id,
            action: "status",
            old_value: "in_progress",
            new_value: "fixed",
            user_id: ticket.assigned_to ?? ticket.created_by,
            created_at: ticket.fixed_at,
            user: demoProfiles.find((profile) => profile.id === (ticket.assigned_to ?? ticket.created_by)),
          },
        ]
      : []),
    ...(ticket.verified_at
      ? [
          {
            id: `${ticket.id}-a4`,
            ticket_id: ticket.id,
            action: "status",
            old_value: "fixed",
            new_value: "verified",
            user_id: ticket.created_by,
            created_at: ticket.verified_at,
            user: demoProfiles.find((profile) => profile.id === ticket.created_by),
          },
        ]
      : []),
  ],
}));
