import type { Profile } from "../types/user";
import type { Ticket } from "../types/ticket";

const now = new Date("2026-05-14T10:30:00.000Z");

function daysAgo(days: number) {
  const date = new Date(now);
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

export const demoProfiles: Profile[] = [
  {
    id: "demo-leader",
    name: "Raj",
    email: "raj@stilldesk.local",
    role: "supreme_leader",
  },
  {
    id: "demo-emma",
    name: "Ava Chen",
    email: "ava@stilldesk.local",
    role: "developer",
  },
  {
    id: "demo-iris",
    name: "Noah Patel",
    email: "noah@stilldesk.local",
    role: "developer",
  },
  {
    id: "demo-reporter",
    name: "Mira Shah",
    email: "mira@stilldesk.local",
    role: "reporter",
  },
];

export const demoUser = demoProfiles[0];

const baseTickets: Ticket[] = [
  {
    id: "SD-1048",
    title: "Emma long prompt reply breaks",
    description:
      "Long prompts render the first response correctly, then the next reply stalls without an error message.",
    category: "ai_agent",
    priority: "high",
    status: "blocked",
    created_by: "demo-reporter",
    assigned_to: "demo-emma",
    module: "Emma",
    dependency_note: "Waiting on token stream timeout details from logs.",
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
    fixed_at: null,
    verified_at: null,
  },
  {
    id: "SD-1047",
    title: "Iris onboarding logo detection failed",
    description: "Company logo detection skips otherwise valid SVG logos on first pass.",
    category: "ai_agent",
    priority: "medium",
    status: "assigned",
    created_by: "demo-reporter",
    assigned_to: "demo-iris",
    module: "Iris",
    dependency_note: null,
    created_at: daysAgo(4),
    updated_at: daysAgo(2),
    fixed_at: null,
    verified_at: null,
  },
  {
    id: "SD-1046",
    title: "Alex enrichment count mismatch",
    description: "The result header says 120 enriched records but the table only shows 116 rows.",
    category: "data",
    priority: "high",
    status: "in_progress",
    created_by: "demo-leader",
    assigned_to: "demo-emma",
    module: "Alex",
    dependency_note: null,
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
    fixed_at: null,
    verified_at: null,
  },
  {
    id: "SD-1045",
    title: "Jim people finder duplicate contacts",
    description: "Duplicate contacts appear when LinkedIn and website sources resolve to the same person.",
    category: "backend",
    priority: "medium",
    status: "open",
    created_by: "demo-reporter",
    assigned_to: null,
    module: "Jim",
    dependency_note: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
    fixed_at: null,
    verified_at: null,
  },
  {
    id: "SD-1044",
    title: "Maya content template preview blank",
    description: "Preview pane is blank after switching template tone from concise to friendly.",
    category: "frontend",
    priority: "medium",
    status: "fixed",
    created_by: "demo-leader",
    assigned_to: "demo-iris",
    module: "Maya",
    dependency_note: null,
    created_at: daysAgo(8),
    updated_at: daysAgo(1),
    fixed_at: daysAgo(1),
    verified_at: null,
  },
  {
    id: "SD-1043",
    title: "Lisa campaign draft missing variable",
    description: "The {{company}} variable is not replaced in the second paragraph of generated drafts.",
    category: "copy",
    priority: "low",
    status: "verified",
    created_by: "demo-reporter",
    assigned_to: "demo-emma",
    module: "Lisa",
    dependency_note: null,
    created_at: daysAgo(10),
    updated_at: daysAgo(2),
    fixed_at: daysAgo(3),
    verified_at: daysAgo(2),
  },
  {
    id: "SD-1042",
    title: "Owen workflow step not updating",
    description: "Changing step owner saves visually but refresh resets it to the previous owner.",
    category: "backend",
    priority: "blocker",
    status: "blocked",
    created_by: "demo-leader",
    assigned_to: "demo-iris",
    module: "Owen",
    dependency_note: "Needs a migration decision for workflow ownership history.",
    created_at: daysAgo(9),
    updated_at: daysAgo(1),
    fixed_at: null,
    verified_at: null,
  },
  {
    id: "SD-1041",
    title: "Mobile pricing CTA overlap",
    description: "On 390px screens, the primary CTA overlaps the plan comparison label.",
    category: "design",
    priority: "medium",
    status: "closed",
    created_by: "demo-reporter",
    assigned_to: "demo-emma",
    module: "Pricing",
    dependency_note: null,
    created_at: daysAgo(14),
    updated_at: daysAgo(4),
    fixed_at: daysAgo(5),
    verified_at: daysAgo(4),
  },
];

export const demoTickets: Ticket[] = baseTickets.map((ticket): Ticket => ({
  ...ticket,
  reporter: demoProfiles.find((profile) => profile.id === ticket.created_by),
  assignee: demoProfiles.find((profile) => profile.id === ticket.assigned_to) ?? null,
  comments: [
    {
      id: `${ticket.id}-c1`,
      ticket_id: ticket.id,
      user_id: ticket.created_by,
      comment: "Raised here so it does not drift across chat.",
      tagged_user_id: ticket.assigned_to,
      created_at: ticket.created_at,
      user: demoProfiles.find((profile) => profile.id === ticket.created_by),
      tagged_user: demoProfiles.find((profile) => profile.id === ticket.assigned_to) ?? null,
    },
  ],
  attachments: [],
  activity: [
    {
      id: `${ticket.id}-a1`,
      ticket_id: ticket.id,
      action: "created",
      old_value: null,
      new_value: ticket.status,
      user_id: ticket.created_by,
      created_at: ticket.created_at,
      user: demoProfiles.find((profile) => profile.id === ticket.created_by),
    },
  ],
}));
